### PR TITLE
Moved StrategyReinvested event to the end

### PR DESCRIPTION
**Pull request by dxganta**
Audit issue [#15](https://github.com/lindy-labs/audit_sandclock/issues/15)

### CODE REVIEW

**Comment by gabrielpoca** [comment]
I'm ok with approving this since it doesn't matter, but why? Readability is the same because you only swapped two lines. I understand the argument for "consistency", but as far as I remember, the standard approach is to emit events before you call external contracts.

**Comment by dxganta** [comment]
I dont mind either way tbh. Looks the same to me.

**Comment by gabrielpoca** [comment]
@fyang1024 since you opened the issue, can you answer here?

**Comment by fyang1024** [comment]
Sorry @gabrielpoca for the late response. Not sure about 

> the standard approach is to emit events before you call external contracts.

I don't know any official standard of this, but looking at openzepplin's contracts, they quite consistently emit `SomethingHappened` event after the code to make it happen, e.g., [the `ERC20PaymentReleased` event is emitted after the ERC20 transfer call](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/591c12d22de283a297e2b551175ccc914c938391/contracts/finance/PaymentSplitter.sol#L183-L184), which is an external contract call

**Comment by gabrielpoca** [comment]
> Sorry @gabrielpoca for the late response. Not sure about
> 
> > the standard approach is to emit events before you call external contracts.
> 
> I don't know any official standard about that tbh, but looking at openzepplin's contracts, they quite consistently emit `SomethingHappened` event after the code to make the 'Something' happen, e.g., [the `ERC20PaymentReleased` event is emitted after the ERC20 transfer call](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/591c12d22de283a297e2b551175ccc914c938391/contracts/finance/PaymentSplitter.sol#L183-L184), which is an external contract call

yeah, must be something wrong I picked up along the way 👍 but why the change then?

**Comment by fyang1024** [comment]
> yeah, must be something wrong I picked up along the way 👍 but why the change then?

Just to maintain the consistency I guess. If there are no other more important changes to the contract, we probably can just leave it. But since we are doing other changes, and it's convenient to make this trivial change, why not?

**Pull request merged**
