### PR TITLE
[L-6] Use type(uint256).max when investing to Yearn Vault

### PR DESCRIPTION
**Pull request by gabrielpoca**
Yearn vaults have a max for deposit amounts. Using `type(uint256).max`
will make the Yearn vault invest the full amount or what is possible.

### CODE REVIEW

**Review by brkomir — APPROVED** [review]
Looks good. I'm thinking should we add a "spy" field on MockYearnVault to make sure we are calling invest() with the uint256.max?

**Review by brkomir — COMMENTED** [review]
On second thought, I think this might cause an issue. Previously, we expected to be able to invest all underlying to Yearn vault, but this is not the case anymore since we can have "leftovers". These leftovers can be indefinitely "locked" in the strategy because when we call withdrawToVault, we are not expecting that there are uninvested underlying held by the strategy and we are trying to withdraw directly from Yearn vault, not accounting for funds possibly held by the strategy.

**Comment by gabrielpoca** [comment]
@brkomir oh, yeah, I forgot about that :+1: we need to bring back that other code we removed then.

**Comment by gabrielpoca** [comment]
@brkomir this should be enough, the change to the invest is already covered by the other tests

**Review by brkomir — APPROVED** [review]
LGTM

**Pull request merged**
