### PR TITLE
fix indexing issue in mock curve pool deploys

### PR DESCRIPTION
**Pull request by coolhill**
This will make sure also mockDAI is deployed and furthermore that mockUSDC is deployed with the correct pool index.

### CODE REVIEW

**Comment by gabrielpoca** [comment]
@coolhill can't we just turn this into a map? it would both avoid this sort of error and also run the loop in parallel, making it run much faster. Unless there's a reason it can't that I'm not seeing

**Comment by coolhill** [comment]
Sure that might work. Although it would be a separate issue, this is just for fixing the indexing bug.

**Review by 0xrin1 — APPROVED** [review]

**Comment by gabrielpoca** [comment]
btw, who's going to run this script?

**Comment by 0xrin1** [comment]
i can deploy another set to staging, should do it in preparation for amethyst deployment imo

**Comment by gabrielpoca** [comment]
In that case, can you incorporate this change into your changes?

**Comment by 0xrin1** [comment]
merged into https://github.com/lindy-labs/sc_solidity-contracts/tree/amethyst-deployment

**Pull request closed without merging**
