### PR TITLE
Inlining some variables

### PR DESCRIPTION
**Pull request by naps62**
On #93 , I was hitting errors due to "deep stack" since I was declaring too many local variables
Turns out that we can actually remove a lot of them, and just copy structs to memory instead of keeping separate variables for each struct element

So I extracted those changes into a separate PR to make things hopefully easier to understand

### CODE REVIEW

**Review by coolhill — APPROVED** [review]
makes sense, good catch

**Comment by coolhill** [comment]
memoizing should not be messed up here right?

**Comment by naps62** [comment]
@coolhill sorry missed your last comment before merging. I don't understand the question though?

**Comment by coolhill** [comment]
We use memoization to avoid gas heavy calls etcetera. local variables to avoid SLOADs or something but I am not super good with it. anyways I added gas monitoring so in the future we can catch stuff like that in CI https://github.com/lindy-labs/sc_solidity-contracts/pull/95

**Pull request merged**
